# Generated by Django 5.2.7 on 2025-10-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registeration_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registeration_method',
            new_name='registration_method',
        ),
    ]
